import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';
import { createServer } from 'http';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
app.use(express.json());

const PORT = parseInt(process.env.WIZARD_PORT || '19090', 10);
const XYVACLAW_HOME = process.env.XYVACLAW_HOME || join(process.env.HOME, '.xyvaclaw');
const WIZARD_CONFIG = process.env.WIZARD_CONFIG || join(XYVACLAW_HOME, '.wizard-config.json');

// Serve static files (built wizard frontend)
const distDir = join(__dirname, '..', 'dist');
if (fs.existsSync(distDir)) {
  app.use(express.static(distDir));
}

// ============================================
// API: Validate API Key
// ============================================
app.post('/api/validate-key', async (req, res) => {
  const { provider, apiKey } = req.body;

  if (!apiKey) {
    return res.json({ valid: false, error: 'No API key provided' });
  }

  try {
    let url, headers, body;

    switch (provider) {
      case 'deepseek':
        url = 'https://api.deepseek.com/v1/chat/completions';
        headers = {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`,
        };
        body = JSON.stringify({
          model: 'deepseek-chat',
          messages: [{ role: 'user', content: 'hi' }],
          max_tokens: 1,
        });
        break;

      case 'bailian':
        url = 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions';
        headers = {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`,
        };
        body = JSON.stringify({
          model: 'qwen-turbo',
          messages: [{ role: 'user', content: 'hi' }],
          max_tokens: 1,
        });
        break;

      case 'feishu': {
        const appId = req.body.appId;
        url = 'https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal';
        headers = { 'Content-Type': 'application/json' };
        body = JSON.stringify({ app_id: appId, app_secret: apiKey });
        break;
      }

      default:
        // Generic OpenAI-compatible test
        url = (req.body.baseUrl || '').replace(/\/$/, '') + '/v1/models';
        headers = { Authorization: `Bearer ${apiKey}` };
        body = undefined;
        break;
    }

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);

    const response = await fetch(url, {
      method: body ? 'POST' : 'GET',
      headers,
      body,
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (provider === 'feishu') {
      const data = await response.json();
      return res.json({
        valid: data.code === 0,
        error: data.code !== 0 ? data.msg : undefined,
      });
    }

    // For LLM providers, any 2xx or 4xx with auth error info means the key format is right
    // 200 = valid, 401/403 = invalid key, others = network issue
    if (response.ok) {
      return res.json({ valid: true });
    }

    const status = response.status;
    if (status === 401 || status === 403) {
      return res.json({ valid: false, error: 'Invalid API key (401/403)' });
    }

    // Some providers return 400 for minimal request but key is valid
    if (status === 400) {
      return res.json({ valid: true, note: 'Key accepted (400 on minimal request)' });
    }

    return res.json({ valid: false, error: `HTTP ${status}` });
  } catch (err) {
    return res.json({
      valid: false,
      error: err.name === 'AbortError' ? 'Timeout (10s)' : err.message,
    });
  }
});

// ============================================
// API: Save Config
// ============================================
app.post('/api/save-config', (req, res) => {
  const config = req.body;

  try {
    // Save wizard config JSON for the installer to consume
    fs.mkdirSync(dirname(WIZARD_CONFIG), { recursive: true });
    fs.writeFileSync(WIZARD_CONFIG, JSON.stringify(config, null, 2));

    // Also generate .env file for the installer
    const envLines = [];
    envLines.push('# Generated by xyvaClaw Setup Wizard');
    envLines.push(`# ${new Date().toISOString()}`);
    envLines.push('');

    if (config.providers?.deepseek?.enabled && config.providers.deepseek.apiKey) {
      envLines.push(`DEEPSEEK_API_KEY=${config.providers.deepseek.apiKey}`);
    }
    if (config.providers?.bailian?.enabled && config.providers.bailian.apiKey) {
      envLines.push(`BAILIAN_API_KEY=${config.providers.bailian.apiKey}`);
    }
    if (config.channels?.feishu?.enabled) {
      if (config.channels.feishu.appId) {
        envLines.push(`FEISHU_APP_ID=${config.channels.feishu.appId}`);
      }
      if (config.channels.feishu.appSecret) {
        envLines.push(`FEISHU_APP_SECRET=${config.channels.feishu.appSecret}`);
      }
    }
    if (config.gateway?.port) {
      envLines.push(`GATEWAY_PORT=${config.gateway.port}`);
    }
    if (config.assistantName) {
      envLines.push(`ASSISTANT_NAME=${config.assistantName}`);
    }

    envLines.push('');

    const envPath = join(XYVACLAW_HOME, '.env');
    fs.writeFileSync(envPath, envLines.join('\n'));

    console.log(`[wizard] Config saved to ${WIZARD_CONFIG}`);
    console.log(`[wizard] Env saved to ${envPath}`);

    res.json({ ok: true });

    // Shut down wizard server after a short delay
    setTimeout(() => {
      console.log('[wizard] Configuration complete. Shutting down wizard server...');
      process.exit(0);
    }, 2000);
  } catch (err) {
    console.error('[wizard] Save error:', err);
    res.json({ ok: false, error: err.message });
  }
});

// ============================================
// API: Get available skills list
// ============================================
app.get('/api/skills', (req, res) => {
  const skillsDir = join(XYVACLAW_HOME, 'workspace', 'skills');
  try {
    if (!fs.existsSync(skillsDir)) {
      return res.json({ skills: [] });
    }
    const dirs = fs.readdirSync(skillsDir, { withFileTypes: true });
    const skills = dirs
      .filter((d) => d.isDirectory() && !d.name.startsWith('_') && d.name !== 'output')
      .map((d) => {
        const metaPath = join(skillsDir, d.name, '_meta.json');
        let meta = {};
        if (fs.existsSync(metaPath)) {
          try {
            meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
          } catch {}
        }
        return { id: d.name, ...meta };
      });
    res.json({ skills });
  } catch (err) {
    res.json({ skills: [], error: err.message });
  }
});

// SPA fallback
app.get('*', (req, res) => {
  const indexPath = join(distDir, 'index.html');
  if (fs.existsSync(indexPath)) {
    res.sendFile(indexPath);
  } else {
    res.status(200).send(`
      <html>
        <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0;">
          <div style="text-align: center;">
            <h1>xyvaClaw Setup Wizard</h1>
            <p>Frontend not built yet. Run <code>cd setup-wizard && npm run build</code> first.</p>
            <p>Or run <code>npm run dev</code> for development mode.</p>
          </div>
        </body>
      </html>
    `);
  }
});

// Start server
const server = createServer(app);
server.listen(PORT, () => {
  console.log(`\n  🐾 xyvaClaw Setup Wizard`);
  console.log(`  ========================`);
  console.log(`  URL: http://localhost:${PORT}`);
  console.log(`  Home: ${XYVACLAW_HOME}`);
  console.log(`\n  Open the URL above in your browser to configure xyvaClaw.\n`);
});
