#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "weasyprint>=62.0",
#     "markdown>=3.5",
# ]
# ///
"""
MD → PDF 可靠转换管道
2026-04-01 P2修复

将 Markdown 文件转为带格式的 PDF，支持中文、表格、代码高亮。

用法:
  python3 md_to_pdf.py input.md                     # 输出到同目录 input.pdf
  python3 md_to_pdf.py input.md -o report.pdf       # 指定输出路径
  python3 md_to_pdf.py input.md --title "月度报告"   # 添加封面标题
  echo "# Hello" | python3 md_to_pdf.py - -o out.pdf # 从stdin读取
"""

import argparse
import os
import sys
from pathlib import Path

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"
OUTPUT_DIR = Path.home() / ".openclaw" / "output" / "docs"


def load_css() -> str:
    """加载 base.css，失败则用内置 fallback"""
    css_path = TEMPLATES_DIR / "base.css"
    if css_path.exists():
        return css_path.read_text(encoding="utf-8")
    return """
@page { size: A4; margin: 2cm 2.5cm; }
body {
    font-family: "Heiti SC", "STHeiti", "Noto Sans CJK SC", "Source Han Sans CN",
                 "Microsoft YaHei", sans-serif;
    font-size: 11pt; line-height: 1.8; color: #333;
}
h1 { font-size: 22pt; color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 8px; }
h2 { font-size: 16pt; color: #16213e; margin-top: 1.5em; }
h3 { font-size: 13pt; color: #0f3460; }
table { width: 100%; border-collapse: collapse; margin: 1em 0; font-size: 10pt; }
th { background: #16213e; color: white; padding: 8px 12px; text-align: left; }
td { padding: 6px 12px; border-bottom: 1px solid #ddd; }
tr:nth-child(even) { background: #f8f9fa; }
code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 10pt; font-family: "Menlo", "Monaco", "Courier New", "Heiti SC", "Noto Sans CJK SC", monospace; }
pre { background: #f8f9fa; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 9.5pt; font-family: "Menlo", "Monaco", "Courier New", "Heiti SC", "Noto Sans CJK SC", monospace; }
blockquote { border-left: 4px solid #16213e; padding-left: 1em; color: #555; }
"""


def md_to_html(md_text: str) -> str:
    """Markdown → HTML (带扩展)"""
    import markdown
    extensions = ["tables", "fenced_code", "codehilite", "toc", "nl2br", "sane_lists"]
    return markdown.markdown(md_text, extensions=extensions)


def build_full_html(body_html: str, title: str = "", css: str = "") -> str:
    """组装完整 HTML 文档"""
    title_block = ""
    if title:
        title_block = f'''<div style="text-align:center; padding-top:25%; page-break-after:always;">
<h1 style="font-size:28pt; border:none;">{title}</h1>
<p style="color:#666; font-size:12pt; margin-top:2em;">Generated by OpenClaw</p>
</div>'''
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>{css}</style></head>
<body>{title_block}{body_html}</body></html>"""


def convert(md_text: str, output_path: str, title: str = "") -> dict:
    """核心转换函数"""
    from weasyprint import HTML

    css = load_css()
    body = md_to_html(md_text)
    html = build_full_html(body, title=title, css=css)

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    HTML(string=html).write_pdf(str(out))
    size_kb = out.stat().st_size / 1024
    return {"success": True, "path": str(out.resolve()), "size_kb": round(size_kb, 1)}


def main():
    parser = argparse.ArgumentParser(description="MD → PDF 转换器")
    parser.add_argument("input", help="Markdown 文件路径 (用 '-' 从 stdin 读取)")
    parser.add_argument("-o", "--output", help="输出 PDF 路径")
    parser.add_argument("--title", default="", help="封面标题")
    args = parser.parse_args()

    # 读取输入
    if args.input == "-":
        md_text = sys.stdin.read()
        if not args.output:
            OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
            args.output = str(OUTPUT_DIR / "stdin_output.pdf")
    else:
        inp = Path(args.input)
        if not inp.exists():
            print(f"❌ 文件不存在: {args.input}", file=sys.stderr)
            sys.exit(1)
        md_text = inp.read_text(encoding="utf-8")
        if not args.output:
            args.output = str(inp.with_suffix(".pdf"))

    result = convert(md_text, args.output, title=args.title)
    if result["success"]:
        print(f"✅ PDF 已生成: {result['path']} ({result['size_kb']} KB)")
        print(f"MEDIA: {result['path']}")
    else:
        print("❌ 转换失败", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
